replicaCount: 2

image:
  repository: registry.digitalocean.com/ruhi-creg/hextris-app
  tag: "latest"
  pullPolicy: Always # Set to IfNotPresent, if you don't want to pull the images each time

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: roohi.mecarvi.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hextris-tls
      hosts:
        - roohi.mecarvi.com
